# Generated by Django 3.2 on 2023-01-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('confirmation_code',), 'verbose_name': 'Пользователи'},
        ),
    ]
